version: "3.9"
services:

  front:
    container_name: clicker_front
    restart: always
    command: serve -s dist
    build: .
    volumes:
      - ./dist:/src/dist
    stdin_open: true
    tty: true
    networks:
      tnets:
        ipv4_address: 172.16.1.3

networks:
  tnets:
    external: true
